// <auto-generated />
using Codesanook.EFNote.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CompiledModels
{
    [DbContext(typeof(NoteDbContext))]
    public partial class NoteDbContextModel : RuntimeModel
    {
        static NoteDbContextModel()
        {
            var model = new NoteDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static NoteDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
