// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CompiledModels
{
    public partial class NoteDbContextModel
    {
        partial void Initialize()
        {
            var note = NoteEntityType.Create(this);
            var notebook = NotebookEntityType.Create(this);
            var tag = TagEntityType.Create(this);
            var noteTag = NoteTagEntityType.Create(this);

            NoteEntityType.CreateForeignKey1(note, notebook);
            NoteTagEntityType.CreateForeignKey1(noteTag, note);
            NoteTagEntityType.CreateForeignKey2(noteTag, tag);

            NoteEntityType.CreateSkipNavigation1(note, tag, noteTag);
            TagEntityType.CreateSkipNavigation1(tag, note, noteTag);

            NoteEntityType.CreateAnnotations(note);
            NotebookEntityType.CreateAnnotations(notebook);
            TagEntityType.CreateAnnotations(tag);
            NoteTagEntityType.CreateAnnotations(noteTag);

            AddAnnotation("ProductVersion", "6.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
