// <auto-generated />
using System;
using Codesanook.EFNote.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Codesanook.EFNote.Migrations
{
    [DbContext(typeof(NoteDbContext))]
    [Migration("20210616222158_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Codesanook.EFNote.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int>("NotebookId")
                        .HasColumnType("int")
                        .HasColumnName("notebook_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_utc");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_note");

                    b.HasIndex("NotebookId")
                        .HasDatabaseName("ix_note_notebook_id");

                    b.ToTable("note");

                    b
                        .HasAnnotation("MySQL:Charset", "utf8mb4")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Codesanook.EFNote.Models.Notebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_notebook");

                    b.ToTable("notebook");

                    b
                        .HasAnnotation("MySQL:Charset", "utf8mb4")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("Codesanook.EFNote.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.ToTable("tag");

                    b
                        .HasAnnotation("MySQL:Charset", "utf8mb4")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("NoteTag", b =>
                {
                    b.Property<int>("NotesId")
                        .HasColumnType("int")
                        .HasColumnName("notes_id");

                    b.Property<int>("TagsId")
                        .HasColumnType("int")
                        .HasColumnName("tags_id");

                    b.HasKey("NotesId", "TagsId")
                        .HasName("pk_note_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_note_tag_tags_id");

                    b.ToTable("note_tag");
                });

            modelBuilder.Entity("Codesanook.EFNote.Models.Note", b =>
                {
                    b.HasOne("Codesanook.EFNote.Models.Notebook", "Notebook")
                        .WithMany("Notes")
                        .HasForeignKey("NotebookId")
                        .HasConstraintName("fk_note_notebook_notebook_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("NoteTag", b =>
                {
                    b.HasOne("Codesanook.EFNote.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("NotesId")
                        .HasConstraintName("fk_note_tag_notes_notes_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codesanook.EFNote.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .HasConstraintName("fk_note_tag_tags_tags_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Codesanook.EFNote.Models.Notebook", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
